my_project/blog/urls.py
from django.urls import path
from blog.views import home, posts, browser


app_name = 'blog'
urlpatterns = [
    path('', home, name='home'),
    path('posts', posts, name='posts'),
    path('browser', browser, name='browser'),
]

my_project/my_project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('blog/', include('blog.urls')),
    path('admin/', admin.site.urls),
]

my_project/blog/models.py
from django.db import models
import datetime

class blogs(models.Model):
    article_name = models.CharField('article_name', max_length=200, primary_key=True) #this is article name, let's set it for primary_key
    plain_text = models.TextField('plain_text', null=False) #this is article, we use TextField cause it can cantain a lot.
    post_time = models.DateTimeField('post_time', default=datetime.datetime.now()) #artice post time
    #this part is set up for the forms. Talk about it later.....
    def __str__(self):
        return self.article_name

my_project/blog/forms.py
from django import forms
from blog.models import blogs
from django.core.exceptions import ValidationError

class Article_name(forms.Form):
    article_name = forms.ModelChoiceField(queryset=blogs.objects.all(),empty_label="Please choose one",widget=forms.Select(
                                             attrs={'class': 'selectpicker bla bla bli',"data-live-search":"true"}))

class Post_new(forms.Form):
    title = forms.CharField(max_length=100) #New article title
    plain = forms.CharField(widget=forms.Textarea(attrs={'class': 'form-control'})) #new article content
    #form validation for unique title name
    def clean_title(self):
        title = self.cleaned_data['title']
        if blogs.objects.filter(article_name=title).exists():
            raise forms.ValidationError('The article has been posted, please change another name')
        return title

my_project/blog/views.py
from django.shortcuts import render
from blog.forms import *
from blog.models import *
from django.core.exceptions import ValidationError
# Create your views here.

def home(request):
    return render(request, 'home.html')

def browser(request):
    form = Article_name()
    result = {}
    if 'submit' in request.POST:
        try:
            blog = list(blogs.objects.filter(article_name=
                                             request.POST['article_name']).values('article_name','plain_text'))
        except Exception as e:
            raise e
        if blog:
            result['title'] = blog[0]['article_name']
            result['content'] = blog[0]['plain_text']

            return render(request, 'result2.html', {'form': result})



    return render(request, 'browser.html',{'form':form})

def posts(request):
    form = Post_new()
    if request.POST:
        f = Post_new(request.POST)
        if f.is_valid():
            if 'submit' in request.POST:
                blog = blogs()
                blog.article_name = request.POST['title']
                blog.plain_text = request.POST['plain']
                try:
                    blog.save()
                    return render(request, 'result.html', {'form': 'Post successfully'})
                except Exception as e:
                    raise e
        else:
            return render(request, 'result2.html', {'form': 'The article has been posted, please change another name'})
    return render(request, 'post.html',{'form':form})

my_project/blog/templates/browser.html
{% extends 'home.html' %}
{% block content %}
<body>
    <div id="page-wrapper">
            <div class="row">
                <div class="col-lg-12">
                    <h2 class="page-header">Get article</h2>
                </div>





    <form action="{% url 'blog:browser' %}" enctype="multipart/form-data" method="post">
    <table width="100%" class="table table-striped table-bordered table-hover" id="dataTables-example">

       {% csrf_token %}

        {{ form }}

    </table>

    <input type="submit" value="submit" name= "submit" class="btn btn-success"/>
    <input type="reset" value="reset" class="btn btn-warning" />

</form>


  <div class="panel-body">
  {% if messages %}
    {% for message in messages %}
    <div {% if message.tags %} class="alert alert-danger alert-dismissable" {% endif %}>
        {{ message }}</div>
    {% endfor %}
{% endif %}
</div>

{% endblock %}

my_project/blog/templates/home.html
<!DOCTYPE html>
<html lang="en">

<head>
	<title>Pythoncoding.cn</title>
	<meta charset="utf-8" />
	<link rel="stylesheet" href="/static/css/bootstrap.min.css" type = "text/css"/>
	<meta name="viewport" content = "width=device-width, initial-scale=1.0">

	<style type="text/css">
		html,
		body {
		  height:100%
		}
	</style>
</head>

<body class="body" style="background-color:#f6f6f6">
	<div class="container-fluid" style="min-height:95%; ">
		<div class="row">
			  <div class="col-sm-2">
				  <br>
				  <center>
					<img src="/static/images/watchdog.jpg" class="responsive-img" style="width:200px; height:120px">
				  </center>
			  </div>
			  <div class="col-sm-10">
				  <br>
				  <center>
				  <h3>Hi everyone!</h3>
				  </center>
			  </div>
		</div><hr>

		<div class="row">
		  <div class="col-sm-2">
		  <br>

		  <br>
		   <!-- Great, til you resize. -->
			<!--<div class="well bs-sidebar affix" id="sidebar" style="background-color:#fff">-->
			<div class="well bs-sidebar" id="sidebar" style="background-color:#fff">
			  <ul class="nav nav-pills nav-stacked">
				<li><a href="{% url 'blog:browser' %}">Browse</a></li>
				<li><a href="{% url 'blog:posts' %}">Post</a></li>
			  </ul>
			</div> <!--well bs-sidebar affix-->
		  </div> <!--col-sm-2-->
		  <div class="col-sm-10">

			<div class='container-fluid'>
			<br><br>
			   {% block content %}
			   {% endblock %}
			</div>
		  </div>
		</div>
	</div>
	<footer>
		<div class="container-fluid" style='margin-left:15px'>
			<p><a href="#" target="blank">Contact</a> </p>
		</div>
	</footer>

</body>

</html>

my_project/blog/templates/post.html
{% extends 'home.html' %}
{% block content %}
<body>
    <div id="page-wrapper">
            <div class="row">
                <div class="col-lg-12">
                    <h2 class="page-header">Post new article</h2>
                </div>





    <form action="{% url 'blog:posts' %}" enctype="multipart/form-data" method="post">
    <table width="100%" class="table table-striped table-bordered table-hover" id="dataTables-example">

       {% csrf_token %}

        {{ form }}

    </table>

    <input type="submit" value="submit" name= "submit" class="btn btn-success"/>
    <input type="reset" value="reset" class="btn btn-warning" />

</form>


  <div class="panel-body">
  {% if messages %}
    {% for message in messages %}
    <div {% if message.tags %} class="alert alert-danger alert-dismissable" {% endif %}>
        {{ message }}</div>
    {% endfor %}
{% endif %}
</div>

{% endblock %}

my_project/blog/templates/result.html
{% extends 'home.html' %}
{% block content %}
<body>
    <div id="page-wrapper">
            <div class="row">
                <div class="col-lg-12">
                    <h2 class="page-header">result</h2>
                </div>





    <form  enctype="multipart/form-data" method="post">
    <table width="100%" class="table table-striped table-bordered table-hover" id="dataTables-example">

       {% csrf_token %}

        {{ form }}

    </table>
</form>


  <div class="panel-body">
  {% if messages %}
    {% for message in messages %}
    <div {% if message.tags %} class="alert alert-danger alert-dismissable" {% endif %}>
        {{ message }}</div>
    {% endfor %}
{% endif %}
</div>
            {% url 'blog:browser' as the_url %}
                        {% if the_url %}
                     <h3 > <a href="{{ the_url }}">Check the article </a></h3>
                        {% endif %}

{% endblock %}

my_project/blog/templates/result2.html
{% extends 'home.html' %}
{% block content %}
<body>
    <div id="page-wrapper">
            <div class="row">
                <div class="col-lg-12">
                    <h2 class="page-header">{{ form.title }}</h2>
                </div>





    <form  enctype="multipart/form-data" method="post">
    <table width="100%" class="table table-striped table-bordered table-hover" id="dataTables-example">

       {% csrf_token %}
        <p>{{ form.content }}</p>

    </table>
</form>


  <div class="panel-body">
  {% if messages %}
    {% for message in messages %}
    <div {% if message.tags %} class="alert alert-danger alert-dismissable" {% endif %}>
        {{ message }}</div>
    {% endfor %}
{% endif %}
</div>


{% endblock %}